# Generated by Django 2.1.4 on 2019-01-24 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlLongue', models.URLField(unique=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('pseudo', models.CharField(max_length=42)),
                ('nbAcces', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mini-URL',
                'ordering': ['date'],
            },
        ),
    ]
