# Generated by Django 2.1.4 on 2018-12-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181214_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Categorie'},
        ),
    ]
