# Generated by Django 2.1.4 on 2018-12-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_listearticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
